import palette from "../../brand/palette.json";

type Theme = (typeof palette.themes)[keyof typeof palette.themes];

function themeBlock(selector: string, t: Theme): string {
  const fingers = Object.entries(palette.fingerHues)
    .map(([name, hue]) => `  --finger-${name}: hsl(${hue} ${t.fingerS} ${t.fingerL});`)
    .join("\n");
  return `${selector} {
  color-scheme: ${t.scheme};
  --canvas: ${t.canvas};
  --surface: ${t.surface};
  --line: ${t.line};
  --text: ${t.text};
  --dim: ${t.dim};
  --muted: ${t.muted};
  --accent: ${t.accent};
  --accent-ink: ${t.accentInk};
  --error: ${t.error};
  --error-soft: color-mix(in srgb, ${t.error} 22%, transparent);
  --accent-soft: color-mix(in srgb, ${t.accent} 16%, transparent);
${fingers}
}`;
}

/** Generates src/styles/themes.css from brand/palette.json. Never edit that file by hand. */
export function renderThemesCss(): string {
  const entries = Object.entries(palette.themes);
  const blocks = entries.map(([name, t]) =>
    themeBlock(
      name === palette.defaultTheme ? `:root,\n[data-theme="${name}"]` : `[data-theme="${name}"]`,
      t,
    ),
  );
  return `/* Generated by \`npm run brand\` from brand/palette.json. Do not edit. */\n\n${blocks.join("\n\n")}\n`;
}
